import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/Navbar/Navbar";
import TopBanner from "@/components/TopBanner/TopBanner";
import Blogs from "@/components/Blogs/Blogs";
import BottomBanner from "@/components/BottomBanner/BottomBanner";
import Destination from "@/components/Destination/Destination";
import Title from "@/Title/Title";
import Category from "@/components/Category/Category";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
      <Navbar/>
      <TopBanner/>
      <Blogs/>
      <BottomBanner/>
      <Title title={"Destination"} subTitle={"Tick one more destination off of your bucket list with one of our most popular vacations in 2022"}/>
      <Destination/>
      <Category/>
      <Footer/>
      </div>
    </>
  );
}
